### ISSUE TITLE
Context does not start with "//"

### ISSUE THREAD

**Issue by ttho** [ShapeChange/ShapeChange#12]
Many Schematron rules "in the wild" use the context "Element" which is intended to mean "//Element" (rather than "/Element" which would be the correct resolution in a document context). This is party due do bad examples in the Schematron specification, and also a side-effect of the XSLT implementation of Schematron.

The context XPath expressions generated by ShapeChange should not expect Schematron to be evaluated by the ISO Schematron XSLT scripts, but adhere strictly to the XPath 2.0 standard.

**Comment by jechterhoff** [comment]
Hi Timo.

The conversion rule http://shapechange.net/targets/xsd/extensions/#rule-xsd-pkg-schematron references ISO Schematron and converts OCL constraints accordingly.

The ['First Order Logic (FOL) to Schematron' target](http://shapechange.net/targets/first-order-logic-fol-to-schematron/) also converts FOL constraints to ISO Schematron, with queryBinding="xslt2". That wasn't clearly documented so far - I just edited the documentation to fix that.

So, ShapeChange currently derives ISO Schematron. XSLT 1.0 is the default and only normative query binding defined by the ISO Schematron standard. In addition, a reference implementation for "xslt2" as query binding exists and that query binding is often supported. ShapeChange outputs Schematron for these two bindings ('xslt' and 'xslt2' for the XML Schema target, depending upon the requirements, and 'xslt2' for the FOL to Schematron target).

**Comment by jechterhoff** [comment]
By the way: we can discuss adding support for a new query binding - especially if an XSLT based implementation should be avoided in favor of a pure XPath based implementation. That binding should support the requirements of the ISO Schematron standard (so that there's a well defined technological basis) and be specified in detail in a publicly accessible document.

**Comment by vog** [comment]
This is related to #13.

Since the above proposal is fully backwards-compatible (i.e. works with XSLT-based and non-XSLT-based Schematron), couldn't we simply make the "xslt2" binding more compatible with pure XPath, rather than creating an entirely new binding?

**Comment by jechterhoff** [comment]
As I mentioned in #13 the context of this issue apparently is the FOL to Schematron target.

The xslt(2) binding is based on XSLT. :-) Can you give an example of the original Schematron that is or would be created by ShapeChange and then how you'd like it to look (with '//')?

**Comment by vog** [comment]
So this is a typical Schematron context created by ShapeChange:

    aixm:AirportHeliport

To be portable (i.e. non-XSLT-specific), it should be:

    //aixm:AirportHeliport

This is a more elaborate example, not sure if this could acutally be the output by ShapeChange:

    aixm:AirportHeliport/aixm:timeSlice/*  |  aixm:Airspace/aixm:timeSlice/*

The improved version would be:

    //aixm:AirportHeliport/aixm:timeSlice/*  |  //aixm:Airspace/aixm:timeSlice/*

**Comment by jechterhoff** [comment]
How about an XSL transformation as a postprocessing step that converts the output generated by the FOL 2 Schematron target to a format that contains the XPath checks you desire? Something like:

~~~
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:sch="http://purl.oclc.org/dsdl/schematron" xmlns:ex="http://shapechange.net/example"
  exclude-result-prefixes="xs" version="2.0">
  <xsl:output method="xml" indent="yes"/>
  <xsl:template match="sch:schema">
    <ex:rules>
      <xsl:for-each select="current()/sch:pattern/sch:rule">
        <xsl:variable name="rule" select="."/>
        <xsl:for-each select="sch:assert">
          <xsl:variable name="assert" select="."/>
          <xsl:element name="ex:rule">
            <xsl:attribute name="id" select="$assert/@id"/>
            <xsl:attribute name="xpath2_test"
              select="concat('//',$rule/@context,'[not(',replace($assert/@test, 'current\(\)','.'),')]')"/>
            <xsl:value-of select="$assert/text()"/>
          </xsl:element>
        </xsl:for-each>
      </xsl:for-each>
    </ex:rules>
  </xsl:template>
</xsl:stylesheet>
~~~

**Comment by vog** [comment]
We are already doing such a post-processing in the import stage of our validation platform.

The point of this proposal is to get rid of this, by having tool like ShapeChange produce more portable Schematron code in the first place.

**Comment by jechterhoff** [comment]
It's still not clear to me how you'd want to include your modifications - especially altering the rule context - so that the resulting Schematron is "more portable". 

Surely you don't mean to have something like this without using a different queryBinding:

~~~
  <pattern>
    <rule context="//aixm:AerialRefuelling">
      <assert id="AIXM-5.1_RULE-C2562" test="every $x1 in . satisfies (for $c1 in count(for $x2 in $x1/aixm:timeSlice/*/aixm:designatorPrefix return if (not($x2[@xsi:nil='true'])) then 1 else ()) return ($c1 &gt;= 1))">Each AerialRefuelling shall have assigned designatorPrefix value</assert>
    </rule>
~~~

I'm concerned about interoperability here. You want to derive XPath expressions that can directly be executed by a pure XPath engine to identify invalid XML elements. If that was to be achieved with Schematron, an according query binding needs to be specified so that the behavior of pure XPath based Schematron implementations is well defined (in the example, the 'test' expression would be negated and become a predicate expression that is appended to the 'context' - an implementation must know these details to function properly).

At the moment, the SBVR/FOL grammar is limited. Thus we could exchange 'current()' with '.'. I'm not convinced about the use of '//' to modify the context - if the queryBinding is still 'xslt'. The result would be unexpected if you'd run the example with the XSLT reference implementation. 
You might say that we can use '/' as the context, and identify the elements within the 'test' expression (for example using //xyz:element). For performance reasons, we don't use '/' as rule context if a more specific context is available for assertions. In such a case, an implementation only needs to evaluate the context once, not for all assertions that can be made for that context. This is suitable whenever a more specific context than '/' exists - for example a feature type. 

The SBVR/FOL grammar may evolve in the future, introducing for example variables (not just the helper ones used in the current XPath based quantifications). They could be expressed with Schematron 'let' elements - would you cramp them into the 'test' expression of assert elements?

It feels like it would be easier to create a pure FOL-to-XPath2 target (so that we don't run into any issues with Schematron requirements). Such a dedicated target would fulfill your implementation requirements best (no need to parse the Schematron - just directly get XPath expressions to identify invalid elements).

Alternatively, including a postprocessing step to convert the Schematron created by the FOL-to-Schematron target to suit the needs of your implementation is a valid approach.

**Comment by jechterhoff** [comment]
What I said isn't entirely correct: because the test expression currently iterates over the context using a universal quantification, using '//xyz:element' can work. Still, an evolution of the SBVR/FOL grammar may break this.

**Comment by jechterhoff** [comment]
Since there has not been more discussion for over a year, I'm closing this issue.
