### ISSUE TITLE
Ontology target : WARN  BaseXMLWriter:81 - Cannot block rule <http://www.w3.org/TR/rdf-syntax-grammar#daml:collection>

### ISSUE THREAD

**Issue by rmitanch** [ShapeChange/ShapeChange#164]
Hi,
Although the ontology target looks correct (but see below / , I have the following warning (x2)
WARN  BaseXMLWriter:81 - Cannot block rule <http://www.w3.org/TR/rdf-syntax-grammar#daml:collection>
I cannot figure whether I'm doing something wrong or not...
Can someone help me ?
Thanks in advance
Richard

[config-GraceTHD.zip](https://github.com/ShapeChange/ShapeChange/files/2374611/config-GraceTHD.zip)

**Comment by jechterhoff** [comment]
Apparently, Jena does NOT support blocking daml:collection, contrary to what’s stated on “blockRules” at the bottom of https://jena.apache.org/documentation/io/rdfxml_howto.html 

I tracked it down to Abbreviated.java, more specifically:

@Override
    protected void blockRule(Resource r) {
        if (r.equals(RDFSyntax.sectionReification)) sReification=true;
       // else if (r.equals(RDFSyntax.resourcePropertyElt)) sResourcePropertyElt=true;
        else if (r.equals(RDFSyntax.sectionListExpand)) sListExpand=true;
        else if (r.equals(RDFSyntax.parseTypeLiteralPropertyElt)) sParseTypeLiteralPropertyElt=true;
        else if (r.equals(RDFSyntax.parseTypeResourcePropertyElt)) sParseTypeResourcePropertyElt=true;
        else if (r.equals(RDFSyntax.parseTypeCollectionPropertyElt)) sParseTypeCollectionPropertyElt=true;
        else if (r.equals(RDFSyntax.idAttr)) {
            sIdAttr=true;
            sReification = true;
        }
        else if (r.equals(RDFSyntax.propertyAttr)) sPropertyAttr=true;
        //else if (r.equals(DAML_OIL.collection)) sDamlCollection=true;
        else {
            logger.warn("Cannot block rule <"+r.getURI()+">");
        }
}

As we can see, the code to actually block daml:collection is commented out. It’s unclear why this piece of code is no longer active, even though the documentation says otherwise.

**Comment by rmitanch** [comment]
OK I see, so I just have to ignore such warning message...
Thank you
(BTW, I'm really impressed by ShapeChange functionalities, thanks again 
for such a good work!!!)
**
