### ISSUE TITLE
Question on rule-trf-prop-flatten-measure-typed-properties-add-uom-property

### ISSUE THREAD

**Issue by heidivanparys** [ShapeChange/ShapeChange#267]
I was wondering why the multiplicity of the _uom property is set to 0..1. If the property itself has a multiplicity of 1, then I would expect the _uom property to have a multiplicity of 1 too?

**Comment by jechterhoff** [comment]
Good question. In the conceptual model of ISO 19103, property uom of type Measure has a cardinality of exactly 1.

The rule was introduced last year, as documented in #249. It was part of the work done in the UML-to-GML Application Schema Pilot (UGAS-2020), more specifically the "The Features Core Profile and its encoding in JSON" - see the [UGAS-2020 engineering report, at the end of section 7.3.2.2.1. Measure](https://docs.ogc.org/per/20-012.html#_measure), option "Flat representation". The JSON Schema of the flat representation does not require the "length_uom" property, though it does state that "length" depends on "length_uom" (so if length has a value, so too should length_uom). However, the NOTE at the end of the section states that "[...] uom enums and property dependencies are not created [by ShapeChange]", and that "if it turns out that this is important, then future work can design and implement a solution for achieving the full encoding for a flat measure representation." So essentially, rule-trf-prop-flatten-measure-typed-properties-add-uom-property was introduced to support the initial work on a Features Core Profile and its JSON encoding.

**Comment by jechterhoff** [comment]
(Link to the report has been added to the rule documentation)

Yes, I guess that requiring the .._uom property if the original property is mandatory would work. @cportele What do you think?

**Comment by cportele** [comment]
@jechterhoff - Yes, that sounds good to me.

**Comment by heidivanparys** [comment]
Great, thanks, I'll create a pull request one of the coming days.
