### ISSUE TITLE
Building code in tag 2.13.0 fails

### ISSUE THREAD

**Issue by heidivanparys** [ShapeChange/ShapeChange#338]
There is an issue with the code that uses and/or the version of dependency ldproxy-cfg, see screenshot below. It seems that v2.13.0 was built on a snapshot that differs from the one I can get from https://dl.interactive-instruments.de/repository/maven-snapshots/. In addition, releases should probably be built on stable versions? E.g. 3.3.0 instead of 3.3.0-SNAPSHOT?

Background: I am trying to create a quick fix for a small issue, and want to start from 2.13.0. However, my build fails. I am not familiar with ldproxy-cfg or its dependency, so I'm not sure how to resolve this.

![image](https://github.com/ShapeChange/ShapeChange/assets/11427611/79a10d8e-d654-4bcf-a49a-5904a89ceec9)

**Comment by jechterhoff** [comment]
Sorry to hear that, @heidivanparys. 

Yes, relying on Snapshot functionality in a release is not the best, and should be avoided. It is just that ldproxy-development is highly active, and the according ShapeChange target tries to quickly follow these developments.

In any case, since you try to build from tag 2.13.0 locally, remove line 885 from Ldproxy2Target.java (i.e., delete `.providerType("FEATURE").entityStorageVersion(2).providerType("FEATURE").featureProviderType("SQL")`). Then the error should be fixed. As I was told by my colleage, these are internal properties that are set automatically (but for technical reasons are or were available in the ImmutableFeatureProviderSqlData.Builder). The deletion was introduced in mid December last year (i.e., after the release of 2.13.0), for reference, see commit https://github.com/ShapeChange/ShapeChange/commit/2f967132314b4ef3f65a453775a808feb5e50fa9.

Does that help?

Apologies for the trouble that the Snapshot use caused. I'll try to use a stable version in the next release (either a full release or some unique development snapshot).

**Comment by heidivanparys** [comment]
Ok, that works, thanks for the help.
