### ISSUE TITLE
General - Select ordering method for enumerants in output

### ISSUE THREAD

**Issue by ebadgley** [ShapeChange/ShapeChange#6]
As discussed via private email, it would be useful to have a configuration option (for at least the XSD target) controlling how enumerants are sorted in the target.  This could be alphabetical, by the sequenceNumber tagged value (or by any other chosen tag) or some other approach.

**Comment by jechterhoff** [comment]
This can be implemented as a separate transformation, so that the functionality is available anywhere in the processing chain. 

Note that the background of the enhancement request is comparison of models loaded from different sources. If the sequenceNumber is not explicitly set for enums, this can lead to a different order in an encoding such as XSD - making it more difficult to compare the results that have been derived from the different sources.

**Comment by jechterhoff** [comment]
Closing this very old issue. If the enhancement discussed in this issue is still needed, please reopen the issue.
